package _Self

import buildTypes.*
import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project

object Project : Project({

    buildType(Qodana_1)
    buildType(Cmd)
    buildType(IntellijIDEAProject)
    buildType(OctopusDeployPromoteRelease)
    buildType(PowerShell)
    buildType(NuGetPack)
    buildType(InspectionsIdea)
    buildType(KotlinScript)
    buildType(Rake)
    buildType(DuplicatesFinderJava)
    buildType(OctopusDeployPushPackages)
    buildType(EmptyBuild)
    buildType(Python)
    buildType(DotNET)
    buildType(SmbUpload)
    buildType(SshExec)
    buildType(DuplicatesFinderReSharper)
    buildType(FTPUpload_1)
    buildType(InspectionsReSharper)
    buildType(NuGetPublish)
    buildType(NUnit)
    buildType(NodeJS)
    buildType(Docker)
    buildType(Gradle)
    buildType(OctopusDeployDeployRelease)
    buildType(SshUpload)
    buildType(OctopusDeployBuildInformation)
    buildType(OctopusDeployCreateRelease)
    buildType(SimpleBuildToolScala)
    buildType(Maven)
    buildType(Unity)
    buildType(CScript)
    buildType(NuGetInstaller)
    buildType(MSpec)
    buildType(OctopusDeployPack)
    buildType(ContainerDeployer_1)
    buildType(FxCop)
    buildType(NAnt)
    buildType(XcodeProject)
    buildType(Ant)
    buildType(DockerCompose)
})
